apiVersion: apps/v1
kind: Deployment
metadata:
  name: fhem
spec:
  selector:
    matchLabels:
      app: fhem
  replicas: 1
  minReadySeconds: 10
  template:
    metadata:
      labels:
        app: fhem
    spec:
      terminationGracePeriodSeconds: 10
      hostNetwork: true
      containers:
        - image: ghcr.io/fhem/fhem-docker:3.3.2-bullseye
          name: fhem
          volumeMounts:
            - name: fhem-volume
              mountPath: /opt/fhem
          resources:
            limits:
              memory: 512Mi
              cpu: 500m
          env:
            - name: TZ
              value: Europe/Berlin
            - name: CPAN_PKGS
              value: JSON
            - name: NPM_PKGS
              value: alexa-fhem homebridge-fhem
      volumes:
        - name: fhem-volume
          hostPath:
            path: /var/data/fhem
            type: Directory
