# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "docker"
    schedule:
      interval: "daily"
      time: "19:30"
      timezone: "Europe/Berlin"
    directories:
      - "/argocd"
      - "/argocd/applications"
      - "/evcc"
      - "/fhem"
      - "/grafana"
      - "/homeassistant"
      - "/influxdb"
      - "/jellyfin"
      - "/magicmirror"
      - "/mosquitto"
      - "/nextcloud"
      - "/nodered"
      - "/paperless"
      - "/sae"
      - "/wikijs"
      - "/zigbee2mqtt"