# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - directory: "/evcc"
    package-ecosystem: "docker"
    schedule:
      interval: "daily"
      time: "19:30"
      timezone: "Europe/Berlin"
  - directory: "/fhem"
    package-ecosystem: "docker"
    schedule:
      interval: "daily"
      time: "19:30"
      timezone: "Europe/Berlin"
  - directory: "/grafana"
    package-ecosystem: "docker"
    schedule:
      interval: "daily"
      time: "19:30"
      timezone: "Europe/Berlin"
  - directory: "/homeassistant"
    package-ecosystem: "docker"
    schedule:
      interval: "daily"
      time: "19:30"
      timezone: "Europe/Berlin"
  - directory: "/magicmirror"
    package-ecosystem: "docker"
    schedule:
      interval: "daily"
      time: "19:30"
      timezone: "Europe/Berlin"
  - directory: "/mosquitto"
    package-ecosystem: "docker"
    schedule:
      interval: "daily"
      time: "19:30"
      timezone: "Europe/Berlin"
  - directory: "/nextcloud"
    package-ecosystem: "docker"
    schedule:
      interval: "daily"
      time: "19:30"
      timezone: "Europe/Berlin"
  - directory: "/nodered"
    package-ecosystem: "docker"
    schedule:
      interval: "daily"
      time: "19:30"
      timezone: "Europe/Berlin"
  - directory: "/paperless"
    package-ecosystem: "docker"
    schedule:
      interval: "daily"
      time: "19:30"
      timezone: "Europe/Berlin"
  - directory: "/wikijs"
    package-ecosystem: "docker"
    schedule:
      interval: "daily"
      time: "19:30"
      timezone: "Europe/Berlin"
