apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: homeassistant
spec:
  selector:
    matchLabels:
      app: homeassistant
  serviceName: homeassistant
  replicas: 1
  minReadySeconds: 10 
  template:
    metadata:
      labels:
        app: homeassistant
    spec:
      terminationGracePeriodSeconds: 10
      hostNetwork: true
      containers:
        - image: ghcr.io/home-assistant/home-assistant:2023.7.0
          name: homeassistant
          volumeMounts:
            - name: homeassistant-volume
              mountPath: /config
          resources:
            limits:
              memory: 512Mi
              cpu: 1000m
          env:
            - name: TZ
              value: Europe/Berlin
      volumes:
        - name: homeassistant-volume
          hostPath:
            path: /var/data/homeassistant
            type: Directory