apiVersion: v1
kind: ConfigMap
metadata:
  name: dummy-configmap
data:
  .dockerenv: ""
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: homeassistant
spec:
  selector:
    matchLabels:
      app: homeassistant
  replicas: 1
  template:
    metadata:
      labels:
        app: homeassistant
    spec:
      hostNetwork: true
      initContainers:
        - name: wait-for-postgres
          image: postgres:18-alpine
          imagePullPolicy: IfNotPresent
          command:
            - sh
            - -c
            - |
              echo "Waiting for Postgres (10.1.84.171:5432)..."
              until pg_isready -h 10.1.84.171 -p 5432; do echo "db not ready yet"; sleep 2; done
              echo "db is ready"

        - name: wait-for-mqtt
          image: eclipse-mosquitto:2
          imagePullPolicy: IfNotPresent
          command:
            - sh
            - -c
            - |
              echo "Waiting for MQTT (10.1.84.158:1883)..."
              until mosquitto_pub -h 10.1.84.158 -p 1883 -t 'test/test' -r -n; do
                echo "mosquitto not ready yet, sleeping for 2 seconds";
                sleep 2;
              done
              echo "mosquitto is ready"
      containers:
        - image: ghcr.io/home-assistant/home-assistant:2025.12.1
          name: homeassistant
          volumeMounts:
            - name: homeassistant-volume
              mountPath: /config
            - name: dummy-volume
              mountPath: /.dockerenv
              subPath: .dockerenv
          resources:
            limits:
              memory: 1.5Gi
              cpu: 2
            requests:
              memory: 1.5Gi
              cpu: 500m
          env:
            - name: TZ
              value: Europe/Berlin
      volumes:
        - name: homeassistant-volume
          hostPath:
            path: /var/data/homeassistant
            type: Directory
        - name: dummy-volume
          configMap:
            name: dummy-configmap
