apiVersion: apps/v1
kind: Deployment
metadata:
  name: homeassistant
spec:
  selector:
    matchLabels:
      app: homeassistant
  replicas: 1
  template:
    metadata:
      labels:
        app: homeassistant
    spec:
      hostNetwork: true
      containers:
        - image: ghcr.io/home-assistant/home-assistant:2024.10.3
          name: homeassistant
          volumeMounts:
            - name: homeassistant-volume
              mountPath: /config
          resources:
            limits:
              memory: 1.5Gi
              cpu: 2
          env:
            - name: TZ
              value: Europe/Berlin
      initContainers:
        - name: db-ready
          image: postgres:17.0-alpine
          command:
            - /bin/sh
            - -c
            - |
              until pg_isready -h db -p 5432; do
                echo "Waiting for database to be ready...";
                sleep 2;
              done;
              echo "Database is ready!";
          env:
            - name: POSTGRES_USER
              value: <path:brvault#homeassistant-postgres-user>
            - name: POSTGRES_PASSWORD
              value: <path:brvault#homeassistant-postgres-password>
      volumes:
        - name: homeassistant-volume
          hostPath:
            path: /var/data/homeassistant
            type: Directory
