apiVersion: apps/v1
kind: Deployment
metadata:
  name: mosquitto
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: mosquitto
  template:
    metadata:
      labels:
        app: mosquitto
    spec:
      volumes:
        - name: config-volume
          configMap:
            name: mosquitto-config
      containers:
        - image: eclipse-mosquitto:2.0.22
          name: mosquitto
          resources:
            limits:
              memory: 64Mi
              cpu: 500m
          volumeMounts:
            - mountPath: /mosquitto/config
              name: config-volume
