apiVersion: v1
kind: Pod
metadata:
  name: mosquitto
  labels:
    app: mosquitto
spec:
  volumes:
    - name: config-volume
      configMap:
        name: mosquitto-config
  containers:
    - image: eclipse-mosquitto:2.0.15
      name: mosquitto
      resources:
        limits:
          memory: 64Mi
          cpu: 500m
      volumeMounts:
        - mountPath: /mosquitto/config
          name: config-volume
