apiVersion: v1
kind: Service
metadata:
  name: mosquitto
spec:
  type: LoadBalancer
  ports:
    - name: mqtt
      port: 1883
      targetPort: 1883
    - name: websocket
      port: 9001
      targetPort: 9001
  selector:
    app: mosquitto
