apiVersion: batch/v1
kind: CronJob
metadata:
  name: preview-pre-generate
spec:
  schedule: "*/3 * * * *"
  concurrencyPolicy: Forbid

  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 604800
      template:
        spec:
          volumes:
            - name: nextcloud-volume
              hostPath:
                path: /var/data/nextcloud/storage
                type: Directory
          containers:
          - name: preview-pre-generate
            image: nextcloud:31.0.9
            imagePullPolicy: IfNotPresent
            command:
            - su
            - -s
            - /bin/sh
            - www-data
            - -c
            - ./occ -vvv preview:pre-generate
            volumeMounts:
              - mountPath: "/var/www/html"
                name: nextcloud-volume
          restartPolicy: "Never"
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: preview-generate-all
spec:
  schedule: "0 4 * * 0"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 2678400
      template:
        spec:
          volumes:
            - name: nextcloud-volume
              hostPath:
                path: /var/data/nextcloud/storage
                type: Directory
          containers:
          - name: preview-generate-all
            image: nextcloud:31.0.9
            imagePullPolicy: IfNotPresent
            command:
            - su
            - -s
            - /bin/sh
            - www-data
            - -c
            - ./occ -v preview:generate-all
            volumeMounts:
              - mountPath: "/var/www/html"
                name: nextcloud-volume
          restartPolicy: "Never"
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: db-backup
spec:
  schedule: "0 0 10 * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 604800
      backoffLimit: 0
      template:
        spec:
          containers:
            - image: postgres:17.6-alpine
              name: db
              volumeMounts:
                - name: backup-volume
                  mountPath: /tmp/backup
              resources:
                limits:
                  memory: 396Mi
                  cpu: 1
              command: ["sh", "-c", "pg_dumpall -h db -c --if-exists > /tmp/backup/backup.sql"]
              env:
                - name: PGUSER
                  value: <path:brvault#nextcloud-postgres-user>
                - name: PGPASSWORD
                  value: <path:brvault#nextcloud-postgres-password>
          volumes:
            - name: backup-volume
              hostPath:
                path: /var/data/nextcloud
                type: Directory
          restartPolicy: Never
