apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: db
spec:
  selector:
    matchLabels:
      app: db
  serviceName: db
  replicas: 1
  minReadySeconds: 10
  template:
    metadata:
      labels:
        app: db
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - image: postgres:15.2-alpine
          name: db
          volumeMounts:
            - name: db-volume
              mountPath: /var/lib/postgresql/data
          resources:
            limits:
              memory: 396Mi
              cpu: 1000m
          env:
            - name: POSTGRES_USER
              value: <path:brvault#nextcloud-postgres-user>
            - name: POSTGRES_PASSWORD
              value: <path:brvault#nextcloud-postgres-password>
      volumes:
        - name: db-volume
          hostPath:
            path: /var/data/nextcloud/postgres
            type: Directory
