apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: imaginary
spec:
  scaleTargetRef:
    kind: Deployment
    apiVersion: apps/v1
    name: imaginary
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 50
