apiVersion: apps/v1
kind: Deployment
metadata:
  name: magicmirror
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: magicmirror
  template:
    metadata:
      labels:
        app: magicmirror
    spec:
      volumes:
        - name: magicmirror
          hostPath:
            path: /var/data/magicmirror/
            type: Directory
      containers:
        - image: karsten13/magicmirror:v2.31.0
          name: magicmirror
          resources:
            limits:
              memory: 256Mi
              cpu: 500m
          volumeMounts:
            - mountPath: /opt/magic_mirror/config/config.js
              subPath: config.js
              name: magicmirror
            - mountPath: /opt/magic_mirror/start_script.sh
              subPath: start_script.sh
              name: magicmirror
          env:
            - name: TZ
              value: Europe/Berlin