apiVersion: v1
kind: Service
metadata:
  name: magicmirror
  labels:
    app: magicmirror
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
      name: http
  selector:
    app: magicmirror
