apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodered
spec:
  selector:
    matchLabels:
      app: nodered
  replicas: 1
  minReadySeconds: 10
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: nodered
    spec:
      hostNetwork: true
      containers:
        - image: nodered/node-red:4.0.2
          name: nodered
          volumeMounts:
            - name: nodered-volume
              mountPath: /data
          resources:
            limits:
              memory: 512Mi
              cpu: 500m
            requests:
              memory: 100Mi
              cpu: 50m
          env:
            - name: TZ
              value: Europe/Berlin
      volumes:
        - name: nodered-volume
          hostPath:
            path: /var/data/nodered
            type: Directory
