apiVersion: apps/v1
kind: Deployment
metadata:
  name: evcc
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: evcc
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: evcc
    spec:
      volumes:
        - name: config-volume
          hostPath:
            path: /var/data/evcc/
            type: Directory
      hostNetwork: true
      initContainers:
        - name: wait-for-mqtt
          image: eclipse-mosquitto:2
          imagePullPolicy: IfNotPresent
          command:
            - sh
            - -c
            - |
              echo "Waiting for MQTT (10.1.84.146:1883)..."
              until mosquitto_pub -h 10.1.84.146 -p 1883 -t 'test/test' -r -n; do
                echo "mosquitto not ready yet, sleeping for 2 seconds";
                sleep 2;
              done
              echo "mosquitto is ready"
      containers:
        - image: evcc/evcc:0.210.2
          name: evcc
          resources:
            limits:
              memory: 64Mi
              cpu: 500m
            requests:
              memory: 64Mi
              cpu: 100m
          volumeMounts:
            - name: config-volume
              subPath: evcc.yaml
              mountPath: /etc/evcc.yaml
            - name: config-volume
              mountPath: /root/.evcc/
          env:
            - name: SEMP_BASE_URL
              value: http://192.168.178.10:7070
