apiVersion: apps/v1
kind: Deployment
metadata:
  name: evcc
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: evcc
  template:
    metadata:
      labels:
        app: evcc
    spec:
      volumes:
        - name: config-volume
          hostPath:
            path: /var/data/evcc/
            type: Directory
      hostNetwork: true
      containers:
        - image: evcc/evcc:0.209.6
          name: evcc
          resources:
            limits:
              memory: 64Mi
              cpu: 500m
          volumeMounts:
            - name: config-volume
              subPath: evcc.yaml
              mountPath: /etc/evcc.yaml
            - name: config-volume
              mountPath: /root/.evcc/
          env:
            - name: SEMP_BASE_URL
              value: http://192.168.178.10:7070
