apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/bunnu/home-iac.git
    targetRevision: main
    path: argocd/applications
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
