configs:
  cmp:
    create: true
    plugins:
      argocd-vault-plugin:
        generate:
          args:
            - generate
            - -s
            - argocd-vault-plugin-credentials
            - ./
          command:
            - argocd-vault-plugin
server:
  service:
    type: LoadBalancer
    
repoServer:
  extraContainers:
    - command:
        - /var/run/argocd/argocd-cmp-server
      envFrom:
        - secretRef:
            name: argocd-vault-plugin-credentials
      image: quay.io/argoproj/argocd
      name: avp
      securityContext:
        runAsNonRoot: true
        runAsUser: 999
      volumeMounts:
        - mountPath: /var/run/argocd
          name: var-files
        - mountPath: /home/argocd/cmp-server/plugins
          name: plugins
        - mountPath: /tmp
          name: tmp-dir
        - mountPath: /home/argocd/cmp-server/config/plugin.yaml
          name: cmp-plugin
          subPath: avp.yaml
        - mountPath: /usr/local/bin/argocd-vault-plugin
          name: custom-tools
          subPath: argocd-vault-plugin
  initContainers:
    - args:
        - curl -L https://github.com/argoproj-labs/argocd-vault-plugin/releases/download/v$(AVP_VERSION)/argocd-vault-plugin_$(AVP_VERSION)_linux_amd64
          -o argocd-vault-plugin && chmod +x argocd-vault-plugin && mv argocd-vault-plugin
          /custom-tools/
      command:
        - sh
        - -c
      env:
        - name: AVP_VERSION
          value: 1.17.0
      image: registry.access.redhat.com/ubi8
      name: download-tools
      volumeMounts:
        - mountPath: /custom-tools
          name: custom-tools
  volumes:
    - configMap:
        name: cmp-plugin
      name: cmp-plugin
    - emptyDir: {}
      name: custom-tools
    - emptyDir: {}
      name: tmp-dir
