apiVersion: apps/v1
kind: Deployment
metadata:
  name: sae
spec:
  selector:
    matchLabels:
      app: sae
  replicas: 1
  minReadySeconds: 10
  template:
    metadata:
      labels:
        app: sae
    spec:
      hostNetwork: true
      containers:
        - image: avanux/smartapplianceenabler:2.3.0
          name: sae
          volumeMounts:
            - name: sae-volume
              subPath: data
              mountPath: /opt/sae/data
            - name: sae-volume
              subPath: logback-spring.xml
              mountPath: /opt/sae/logback-spring.xml
            - name: sae-volume
              subPath: logs
              mountPath: /tmp/logs
          resources:
            limits:
              memory: 512Mi
              cpu: 500m
            requests:
              memory: 256Mi
              cpu: 50m
          env:
            - name: TZ
              value: Europe/Berlin
            - name: JAVA_OPTS
              value: "-Dserver.port=8080 -Dserver.address=192.168.178.10 -Dsemp.gateway.address=192.168.178.10 -Djava.net.preferIPv4Stack=true -Xmx196m"
      volumes:
        - name: sae-volume
          hostPath:
            path: /var/data/sae
            type: Directory
