apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: default
  sources:
    - chart: argo-cd
      helm:
        valueFiles:
          - $values/argocd/values.yaml
      repoURL: https://argoproj.github.io/argo-helm
      targetRevision: 6.7.10
    - ref: values
      repoURL: https://github.com/bunnu/home-iac.git
      targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true