apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mosquitto
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/bunnu/home-iac.git
    path: mosquitto
    targetRevision: main
  destination:
    server: https://kubernetes.default.svc
    namespace: mosquitto
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
